name: env_exercise_9
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - blosc=1.20.1=h7bd577a_0
  - brotli=1.0.9=ha925a31_2
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.12.5=py38haa95532_0
  - charls=2.1.0=h33f27b4_2
  - cloudpickle=1.6.0=py_0
  - cycler=0.10.0=py38_0
  - cytoolz=0.11.0=py38he774522_0
  - dask-core=2.30.0=py_0
  - decorator=4.4.2=py_0
  - freetype=2.10.4=hd328e21_0
  - giflib=5.2.1=h62dcd97_0
  - icc_rt=2019.0.0=h0cc432a_1
  - imagecodecs=2020.5.30=py38hb1be65f_2
  - imageio=2.9.0=py_0
  - intel-openmp=2020.2=254
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.3.0=py38hd77b12b_0
  - lcms2=2.11=hc51a39a_0
  - libaec=1.0.4=h33f27b4_1
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - libzopfli=1.0.3=ha925a31_0
  - lz4-c=1.9.2=hf4a77e7_3
  - matplotlib-base=3.3.2=py38hba9282a_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38h196d8e1_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - networkx=2.5=py_0
  - numpy=1.19.2=py38hadc3359_0
  - numpy-base=1.19.2=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openjpeg=2.3.0=h5ec785f_1
  - openssl=1.1.1h=he774522_0
  - pillow=8.0.1=py38h4fa10fc_0
  - pip=20.3.1=py38haa95532_0
  - pyparsing=2.4.7=py_0
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - pywavelets=1.1.1=py38he774522_2
  - pyyaml=5.3.1=py38he774522_1
  - scikit-image=0.17.2=py38h1e1f486_0
  - scipy=1.5.2=py38h14eb087_0
  - setuptools=51.0.0=py38haa95532_2
  - six=1.15.0=py38haa95532_0
  - snappy=1.1.8=h33f27b4_0
  - sqlite=3.33.0=h2a8f88b_0
  - tifffile=2020.12.4=pyhd3eb1b0_0
  - tk=8.6.10=he774522_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h2bbff1b_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.36.1=pyhd3eb1b0_0
  - wincertstore=0.2=py38_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
prefix: C:\Users\rober\miniconda3\envs\env_exercise_9

